
on:
  pull_request:
    branches: [ main ]
    paths: apps/server/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-schema:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      # cspell:ignore Swatinem
      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2

      - run: cargo run --bin schema-gen
        working-directory: apps/server

      - run: git diff --exit-code
