
on:
  pull_request:
    branches: [ main ]
    paths: apps/server/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-schema:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable # cspell:ignore dtolnay
      - uses: Swatinem/rust-cache@v2 # cspell:ignore Swatinem

      - run: cargo run --bin schema-gen
        working-directory: apps/server

      - run: git diff --exit-code
